language: erlang

otp_release:
  - 17.4
  - 18.3
  - 19.3
  - 20.3.8
  - 21.3.8
  - 22.2.8
  - 23.0.4
  

script: rebar3 update && rebar3 eunit && rebar3 dialyzer && rebar3 coveralls send

cache:
  directories:
  - $HOME/.cache/rebar3/
